runners:
  default-arm64:
    cpu: 32
    family: ["c7gd", "m7gd"]
    image: ubuntu24-full-arm64
    extras: ["s3-cache"]
    spot: false

  default-x64:
    cpu: 32
    family: ["c6id", "m6id"]
    image: ubuntu24-full-x64
    extras: ["s3-cache"]
    spot: false

  xlarge-arm64:
    cpu: 64
    family: ["c7gd", "m7gd"]
    image: ubuntu24-full-arm64
    extras: ["s3-cache"]
    spot: false

  xlarge-x64:
    cpu: 64
    family: ["c6id", "m6id"]
    image: ubuntu24-full-x64
    extras: ["s3-cache"]
    spot: false
