runners:
  small-arm64:
    cpu: 16
    family: ["c7gd", "m7gd"]
    image: ubuntu24-full-arm64
    extras: ["s3-cache"]
    spot: false

  small-x64:
    cpu: 16
    family: ["c6id", "c7id", "c7ad"]
    image: ubuntu24-full-x64
    extras: ["s3-cache"]
    spot: false

  large-arm64:
    cpu: 32
    family: ["c7gd", "m7gd"]
    image: ubuntu24-full-arm64
    extras: ["s3-cache"]
    spot: false

  large-x64:
    cpu: 32
    family: ["c6id", "c7id", "c7ad", "m7id", "m7ad"]
    image: ubuntu24-full-x64
    extras: ["s3-cache"]
    spot: false
