runners:
  small-arm64:
    cpu: 16
    family: ["c7g", "m7g"]
    image: ubuntu24-full-arm64
    extras: ["s3-cache"]
    spot: false

  small-x64:
    cpu: 16
    family: ["c7a", "c7i", "m7a"]
    image: ubuntu24-full-x64
    extras: ["s3-cache"]
    spot: false

  large-arm64:
    cpu: 32
    family: ["c7gd", "m7gd"]
    image: ubuntu24-full-arm64
    extras: ["s3-cache"]
    spot: false

  large-x64:
    cpu: 32
    family: ["c7ad", "c7id", "m7id"]
    image: ubuntu24-full-x64
    extras: ["s3-cache"]
    spot: false
