name: QEMU x86-64

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    uses: ./.github/workflows/build-sgl.yml
    with:
      kas_config: sgl-scarthgap-qemux86-64.yml
      hardware_arch: qemux86-64
      runner_arch: x64
